package com.janhafner.myskatemap.apps.activityrecorder

import com.janhafner.myskatemap.apps.activityrecorder.modules.ApplicationModule
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.BurnedEnergyDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.DistanceDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.NumberOfLocationsDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.RecordingTimeDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.altitude.AverageAltitudeDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.altitude.CurrentAltitudeDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.altitude.MaximumAltitudeDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.altitude.MinimumAltitudeDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.speed.AverageSpeedDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.speed.CurrentSpeedDashboardTileFragmentPresenter
import com.janhafner.myskatemap.apps.activityrecorder.views.activities.activityrecorder.dashboard.tiles.speed.MaximumSpeedDashboardTileFragmentPresenter
import dagger.Component
import javax.inject.Singleton

@Singleton
@Component(modules = [ApplicationModule::class])
internal interface DashboardTileFragmentPresenterComponent {
    fun provideAverageAltitudeDashboardTileFragmentPresenter() : AverageAltitudeDashboardTileFragmentPresenter

    fun provideMinimumAltitudeDashboardTileFragmentPresenter() : MinimumAltitudeDashboardTileFragmentPresenter

    fun provideMaximumAltitudeDashboardTileFragmentPresenter() : MaximumAltitudeDashboardTileFragmentPresenter

    fun provideCurrentAltitudeDashboardTileFragmentPresenter() : CurrentAltitudeDashboardTileFragmentPresenter

    fun provideAverageSpeedDashboardTileFragmentPresenter() : AverageSpeedDashboardTileFragmentPresenter

    fun provideMaximumSpeedDashboardTileFragmentPresenter() : MaximumSpeedDashboardTileFragmentPresenter

    fun provideCurrentSpeedDashboardTileFragmentPresenter() : CurrentSpeedDashboardTileFragmentPresenter

    fun provideDistanceDashboardTileFragmentPresenter() : DistanceDashboardTileFragmentPresenter

    fun provideNumberOfLocationsDashboardTileFragmentPresenter() : NumberOfLocationsDashboardTileFragmentPresenter

    fun provideRecordingTimeDashboardTileFragmentPresenter() : RecordingTimeDashboardTileFragmentPresenter

    fun provideBurnedEnergyDashboardTileFragmentPresenter() : BurnedEnergyDashboardTileFragmentPresenter
}